title:              CNCF Articles
email:              vita400@kakao.com
description:        CNCF 아티클 읽어주는 남자
author:             Start Bootstrap
baseurl:            "/cncf-articles"
url:                "https://parkjeongryul.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
